### ISSUE TITLE
Unable to set 1:1 aspect ratio properly on RGB30

### ISSUE THREAD

**Issue by metchebe** [gerudoga/zelda3#1]
### Describe your bug here. And how to reproduce it.

Follow up from: https://github.com/snesrev/zelda3/pull/193#issuecomment-2197386337

Device: Powkiddy RGB30v1
OS: ROCKNIX-RK3566.aarch64-20240612 (SDL 2.30.3)
SDL video driver: kmsdrm

I suspect the issue lies somewhere within this code in `main.c`:
```
static void SdlRenderer_BeginDraw(int width, int height, uint8 **pixels, int *pitch) {
  int shift = 0;
  if (width < 256) {
    shift = (256 - width) / 2;
  }

  g_sdl_renderer_rect_src.x = 0;
  g_sdl_renderer_rect_src.w = width + shift;
  g_sdl_renderer_rect_src.h = height;

  g_sdl_renderer_rect_dst.x = -shift;
  g_sdl_renderer_rect_dst.w = width + shift;
  g_sdl_renderer_rect_dst.h = height;

  if (SDL_LockTexture(g_texture, &g_sdl_renderer_rect_src, (void **)pixels, pitch) != 0) {
    printf("Failed to lock texture: %s\n", SDL_GetError());
    return;
  }
}
```
I managed to relate the horizontal stretching with `shift` by doing some experiments and got more stretching. I tried to fix it but I am simply not knowledgable enough to really understand what is going on.

I can say that the behaviour seems to be that the 240x240 image that should be displayed on screen is stretched to 248x240, which would be `width + shift`.  Then the extra bit on the right gets cut off on the right side of the display.

If I use an aspect ratio a bit wider than 1:1, then `shift` is less, and the stretching is also reduced. When `shift = 0` then there is no stretching beyond the right side of the display. This is why 16:15 works properly.

I also hardcoded `shift = 0` and got an correct unstretched image using 1:1, but with the right 16px cut off (which I expected).

Maybe more debug info on the screen geometry would be useful for me to try to narrow this down.

Anyway, thanks for trying to help.

### What is your build target?

Linux

**Comment by gerudoga** [comment]
I think, I found a hint ... turns out that `EnhancedMode7` is actually influencing the behavior in weird ways.

@metchebe, could you enable it and give 1:1 another go on the RBG30?

What I see is the following:
- `EnhancedMode7 = 1`
  - RGB30 & Ubuntu
    - map is basically unusable (zoomed in too much)
    - screen is properly centered in 1:1
- `EnhancedMode7 = 0`
  - RBG30:
    - map is usable
    - screen is off center
  - Ubuntu:
    - Crashes: `Aborted (core dumped)`

---

I would actually try to fix this, but have a problem. I reinstalled my OS in the meantime and cannot get the cross compiling for ARM to work anymore. @metchebe, I understand you have that working? Can you give me some pointers for how you set it up?

I am relatively sure that last time, I did the following:

1. added `/etc/apt/sources.list.d/arm-cross-compile-sources.list`

```
deb [arch=arm64,armhf] http://ports.ubuntu.com/ noble           main restricted universe multiverse
deb [arch=arm64,armhf] http://ports.ubuntu.com/ noble-backports main restricted universe multiverse
deb [arch=arm64,armhf] http://ports.ubuntu.com/ noble-security  main restricted universe multiverse
deb [arch=arm64,armhf] http://ports.ubuntu.com/ noble-updates   main restricted universe multiverse
```

2. modified `/etc/apt/sources.list.d/official-package-repositories.list` to add `[arch=amd64,i386]`

```
deb [arch=amd64,i386] http://archive.ubuntu.com/ubuntu noble           main restricted universe multiverse
deb [arch=amd64,i386] http://archive.ubuntu.com/ubuntu noble-backports main restricted universe multiverse
deb [arch=amd64,i386] http://archive.ubuntu.com/ubuntu noble-security  main restricted universe multiverse
deb [arch=amd64,i386] http://archive.ubuntu.com/ubuntu noble-updates   main restricted universe multiverse
```

3. installed `aarch64-linux-gnu-gcc` and `libsdl2-dev:arm64`

Now I am failing with `libsdl2-dev:arm64` since apt tries to remove important system packages at that point (for instance, network manager). Any ideas what I am missing would be highly appreciated :)

**Comment by metchebe** [comment]
Hi! Thanks for looking into this.

Yes, indeed enabling enhanced mode 7 acts as you say, confirmed on my RGB30.

For building for my RGB30 I would normally use the Rocknix build system that takes care of cross-compiling an optimized build for this device, however I don't have that set up right now (rebuilding the toolchain takes a while).

For general cross-compiling I use a Debian docker image which has all the architectures in the standard repositories. What you did in Ubuntu though looks fine, I use `crossbuild-essential-arm64` in debian, ubuntu has it also. Those dependency issues are why I use docker.

**Comment by gerudoga** [comment]
Thanks for the ideas! I think I will also try to set up something via the docker route as it sounds less dangerous to accidentally mess up the OS.

I *think* I solved it for now, though:

From what I gathered, the reason could be that the versions of each package needs to be identical for all archs (read in some random stackoverflow answer, so could be wrong). I guess that some package differs such that apt cannot resolve it. Then it removes the amd64 version of it entirely (since I am currently asking for the ARM version to be installed), which then causes the removal of other important packages...

So, I thought, maybe I can just convince it not to do that by asking for the amd64 packages to be installed, too. My first try was changing
```
sudo apt install libsdl2-dev:arm64
```
to
```
sudo apt install libsdl2-dev:arm64 bulky:amd64
```
where `bulky` happened to be the first item on the to-be-removed list... I thought that would maybe give me some indication of why it removed the amd64 packages. But, turns out, that just worked! It only installed the additional ARM packages. So, I can't say I really understand it but I have a working cross compilation setup again.

Back to what I actually wanted to look at :D

**Comment by gerudoga** [comment]
After a bit of code reading, there seemed to be only one place where `EnhancedMode7` plays a special role:

https://github.com/gerudoga/zelda3/blob/377c44db718c9908b1b468ae7099e9f2609092c8/src/main.c#L239

If I hardcode this to `4`, i.e., https://github.com/gerudoga/zelda3/commit/80d29fc1691ece400d2fae6695a764b9fd45f6d1, it works and looks correct. (It actually seems that `2` is enough, just `1` is too small.)

Now for both, RGB30 and Ubuntu, I see the game properly centered regardless of the `EnhancedMode7` setting. The crash on the desktop is gone. @metchebe, it would be great if you could double check that it works for you too with this change :)

(Since you said you don't have the cross compiler set up at the moment, let me know if I should upload the binary...)

The map with enabled EnhancedMode7 is still unusable, though. I suppose for this to be correct, one needs to ignore the `WindowScale` factor (for the RGB30 this is set to `3`) for the map and display/center the internally 4x scaled map at/to the proper resolution. This happens in the low level parts of the code, which I don't understand sufficiently to make any change ATM. If it was possible to use `WindowScale` also there to properly upscale the map, instead of the hardcoded 4x scaling, and then NOT apply `WindowScale` to enlarge the pixels of the map, one would get nice large pixels in-game AND a high-res map. Would be great!

**Comment by metchebe** [comment]
Working ok on RGB30 with your change, thanks. I have a toolchain for my RPi3 and that binary works OK for now.

Now all that's missing is shader support, which I had hoped worked with OpenGL ES but it doesn't :(

I got OpenGL ES working by applying PR #270 but the screen centering only seems to work right with SDL.

**Comment by gerudoga** [comment]
Ah, that's not too surprising... OpenGL has it's own math for which pixel goes where:
https://github.com/gerudoga/zelda3/blob/master/src/opengl.c#L196
This would need to have the same shift logic added as for the SDL part. It would need a bit experimenting for a good place to add it. Might be as easy as adjusting these:
https://github.com/gerudoga/zelda3/blob/master/src/opengl.c#L210
but I haven't tried. I will, if I find the time :)

Funnily, when I looked at it originally, I also noticed the obviously wrong
```
int viewport_y = (viewport_height - viewport_height) >> 1;
```
... that is fixed in the PR you mentioned. But the SDL code was easier to understand, so I only changed that :D

I actually wonder why the PR wasn't accepted at the time.

**Comment by gerudoga** [comment]
Turns out, it was a bit more complicated than for the SDL case ... but, it should work now :)

There's potentially a simpler way to implement it since I now have to recalculate the `WindowScale` parameter in `OpenGLRenderer_EndDraw`, which seems like a bad idea.

Anyway -- as bonus -- for the OpenGL version, the high-res map seems to work correctly.

**Comment by metchebe** [comment]
I made a build of 7517783 for my RGB30 and now, with OpenGL ES, the hi-res map is indeed working correctly, however the screen is still not centered.

**Comment by gerudoga** [comment]
Do you have `StretchToFit = 1` set?

This needs to be disabled, otherwise I am not trying to center the image (I am doing this only for "pixel perfect" mode).

Also, `StretchToFit` enabled doesn't work yet -- it doesn't actually stretch to fit :|
This part is confusing because, from what I see, I didn't change anything for that path of the code...

**Comment by metchebe** [comment]
No, stretch to fit is not set.

I am now getting the following results:

SDL:
* EnhancedMode7 enabled: (centered)
* EnhancedMode7 disabled (not centered)

OpenGL ES:
* Not centered regardless of EnhancedMode7 on or off

**Comment by gerudoga** [comment]
Umm, now I am confused... are you sure you are building the right commit? The SDL code hasn't changed and it was working before, right? As I wrote:

> Now for both, RGB30 and Ubuntu, I see the game properly centered regardless of the EnhancedMode7 setting.

And, I think, you said the same...

**Comment by metchebe** [comment]
Yes indeed, I'm sorry, for some reason I was using an older binary.

I think that the OpenGL ES fix is incomplete in this repo, but the PR as a patch cannot be applied now as-is, so now I only get a black screen in this mode.

I have to fix this to test so I'll get back to you later, thanks.

**Comment by gerudoga** [comment]
Ah, OK. Good you found it.

And yes, I didn't commit the GL_RGBA to GL_BGRA change. Did that now... Also did another round of tests cycling through all parameters. Looks good for me, except `StretchToFit` not working in the OpenGL case. I think, I would need to go back to before all my changes and check if it worked there. I am almost sure it hasn't since I can't see a change to that code path.

Ah, and the high-res map doesn't work correctly via SDL.

**Comment by metchebe** [comment]
Thanks, I have been playing with OpenGL ES and enhanced mode 7 and everything seems OK.

Unfortunately I ran into a game breaking bug in the Tower of Hera (the holes in the floor don't toggle correctly) so my playthrough can't continue. This only happens on arm64, not amd64 on my PC.

**Comment by gerudoga** [comment]
Hmm. In the last two weeks, I actually played and finished the game with the current code using OpenGL ES and enhanced mode 7 on the RGB30. I remember no problems with Tower of Hera.

**Comment by metchebe** [comment]
Yeah, I'm thinking it might be a weird issue caused by the compiler and/or the flags I'm using. I could reproduce this also on my RPi3. I might try a "stock" compiler and see if it makes a difference.

For now I actually used my sram save to get past Tower of Hera on an emulator and then got back to this port to continue. But all this is off topic so I'll mark this as closed, thanks for the fixes.

**Comment by metchebe** [comment]
Followup: I made a straightforward build with the stock crossbuild-essential-arm64 toolchain in a Debian Bookworm container and the floor issue in Tower of Hera is gone.

So, there's some weirdness with the other toolchain I was using. Oh well...
